# przykłady md, python, etc.
## naglowek 2
##### naglowek 5

*italic*

**bold**


> cos
> i dalej

- lista
- lista2

1. numerowane
2. drugi element
3. trzci

```
import numpy as np
print('dupa')
```

równania $ x^2 $

link [google](www.google.com)


In [ ]:
# uzupelnianie stringow
liczby = (0,1,2,3,4,34)
for n in liczby:
    print(f'{n:04d}')

In [5]:
import time

t0=time.time()
time.sleep(1)
t1=time.time()

print(t1-t0)

1.0002150535583496


In [1]:
import numpy as np

data = np.loadtxt("file.dat",usecols=(0,1),unpack=True)
x,y = data[0],data[1]


In [ ]:
# wczytywanie pliku

data = []
f_name = "tmp.txt"
with open(f_name, 'r', encoding='utf-8') as plik:
    for l in plik:
        data.append(l.split()[1])

print(data)

In [13]:
# zapisywanie pliku

res_fname = "tmp.txt"
with open(res_fname, "w") as res_plik:
    res_plik.write(f'1 3 5\n')
    res_plik.write(f'2 4 6\n')
    

In [15]:
# zapisywanie pliku not cool

res_plik = open(res_fname, "w")

res_plik.write(f'1 3 5\n')
res_plik.write(f'2 4 6\n')
res_plik.close()


In [5]:
# lista katalogow

import os

path = "."
katalogi = [d for d in os.listdir(path) if os.path.isdir(path+"/"+d)]

print(katalogi)

['.idea', '.venv', '.git']


In [ ]:
# lista plikow w katalogu

import os

file_list = []
for f in os.listdir("."):
    if f.endswith(".pdf"):
        file_list.append(f)

print(file_list)

In [ ]:
# lista plikow w katalogu i podkatalogach

import os

file_list = []

for root, dirs, files in os.walk("."):
    for f in files:
            if f.endswith(".psf"):
                file_list.append(root+"/"+f)

print(file_list)

In [1]:
# Pasek postepu

import numpy
from tqdm import tqdm

data = numpy.arange(0,43,0.1)

res = 0
for i, val in enumerate(tqdm(data, desc="Processing")): 
    res = res + val

print(res)
    

ModuleNotFoundError: No module named 'tqdm'

In [5]:
# Pasek postepu -  przyklad zaawansowany

import numpy
from tqdm import tqdm

bar = tqdm(total=100)

bar.set_description(f"Step {i}")
bar.update(0)
print("jeden")
bar.update(20)
print("dwa")
bar.update(40)
print("finish")

bar.close()


  0%|          | 0/100 [00:24<?, ?it/s]

Step 429:  60%|██████    | 60/100 [00:00<00:00, 23899.17it/s]

jeden
dwa
finish


In [ ]:
# astropy FITS

from astropy.io import fits

f_name = "plik.fits"

hdul = fits.open(f_name)
data = hdul[0].data
hdr = hdul[0].header
hdul.close()


In [ ]:
# Plot FITS

import numpy as np
import matplotlib.pyplot as plt

image = data

vmin = np.median(image)  - 1 * np.std(image)
vmax = np.median(image)  + 1 * np.std(image)

plt.figure(figsize=(8, 8))
plt.imshow(image,vmin=vmin,vmax=vmax,cmap='binary')
plt.show()


In [1]:
# tworzenie tabeli w fits

import numpy as np
from astropy.io import fits

# dane przykładowe
n = 5
cols = fits.ColDefs([
    fits.Column(name='ID',     format='K', array=np.arange(1, n+1)),
    fits.Column(name='RA',     format='D', array=[10.123, 10.234, 10.345, 10.456, 10.567]),
    fits.Column(name='DEC',    format='D', array=[-5.12, -5.10, -5.08, -5.05, -5.02]),
    fits.Column(name='Vmag',   format='E', array=[15.2, 16.1, 14.8, 15.9, 16.5]),
    fits.Column(name='Jmag',   format='E', array=[14.1, 14.9, 13.8, 14.7, 15.3]),
    fits.Column(name='e_Vmag', format='E', array=[0.03, 0.05, 0.02, 0.04, 0.06]),
    fits.Column(name='e_Jmag', format='E', array=[0.02, 0.03, 0.02, 0.03, 0.04]),
])

hdu = fits.BinTableHDU.from_columns(cols)
hdu.header['EXTNAME'] = 'CATALOG'
hdu.header['COMMENT'] = 'Example photometric catalog'

hdul = fits.HDUList([fits.PrimaryHDU(), hdu])
hdul.writeto('./data/example_catalog.fits', overwrite=True)


In [4]:
# ciakowstka numpy
import numpy as np

a = np.array([[-1,2,3],[1,-2,3],[1,2,-3]])
I = a.clip(min=2)
print(I)


[[2 2 3]
 [2 2 3]
 [2 2 2]]


In [ ]:
# przyklady astropy odleglosci, wysokosci

from astropy.time import Time
import astropy.units as u
from astropy.coordinates import (SkyCoord, EarthLocation, AltAz, get_sun, get_body)

location = EarthLocation(lat=hdr["OBS-LAT"] * u.deg, lon=hdr["OBS-LONG"] * u.deg, height=hdr["OBS-ELEV"] * u.m)
obs_time = Time(hdr["DATE-OBS"], format="isot", scale="utc")
field = SkyCoord(ra=hdr["RA_TEL"] * u.deg, dec=hdr["DEC_TEL"] * u.deg, frame="icrs")

sun = get_sun(obs_time)
moon = get_body("moon", obs_time, location)

altaz_frame = AltAz(obstime=obs_time, location=location)
sun_altaz = sun.transform_to(altaz_frame)
moon_altaz = moon.transform_to(altaz_frame)

print(f"Wysokość Słońca: {sun_altaz.alt.deg:.2f} deg")
print(f"Wysokość Księżyca: {moon_altaz.alt.deg:.2f} deg")

sun_sep = field.separation(sun)
moon_sep = field.separation(moon)

print(f"Odległość pola od Słońca: {sun_sep.deg:.2f} deg")
print(f"Odległość pola od Księżyca: {moon_sep.deg:.2f} deg")





[2, 5, 8]